/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumClaimsRouteImport } from './routes/album-claims'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceCatalogRouteImport } from './routes/marketplace-catalog'
import { Route as MarketplaceInventoryRouteImport } from './routes/marketplace-inventory'
import { Route as MarketplaceOrdersRouteImport } from './routes/marketplace-orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrintOrdersRouteImport } from './routes/print-orders'
import { Route as ReelsCatalogRouteImport } from './routes/reels-catalog'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumClaimsRoute = AlbumClaimsRouteImport.update({
  id: '/album-claims',
  path: '/album-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCatalogRoute = MarketplaceCatalogRouteImport.update({
  id: '/marketplace-catalog',
  path: '/marketplace-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceInventoryRoute = MarketplaceInventoryRouteImport.update({
  id: '/marketplace-inventory',
  path: '/marketplace-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceOrdersRoute = MarketplaceOrdersRouteImport.update({
  id: '/marketplace-orders',
  path: '/marketplace-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOrdersRoute = PrintOrdersRouteImport.update({
  id: '/print-orders',
  path: '/print-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsCatalogRoute = ReelsCatalogRouteImport.update({
  id: '/reels-catalog',
  path: '/reels-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album-claims': typeof AlbumClaimsRoute
  '/login': typeof LoginRoute
  '/marketplace-catalog': typeof MarketplaceCatalogRoute
  '/marketplace-inventory': typeof MarketplaceInventoryRoute
  '/marketplace-orders': typeof MarketplaceOrdersRoute
  '/notifications': typeof NotificationsRoute
  '/print-orders': typeof PrintOrdersRoute
  '/reels-catalog': typeof ReelsCatalogRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album-claims': typeof AlbumClaimsRoute
  '/login': typeof LoginRoute
  '/marketplace-catalog': typeof MarketplaceCatalogRoute
  '/marketplace-inventory': typeof MarketplaceInventoryRoute
  '/marketplace-orders': typeof MarketplaceOrdersRoute
  '/notifications': typeof NotificationsRoute
  '/print-orders': typeof PrintOrdersRoute
  '/reels-catalog': typeof ReelsCatalogRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album-claims': typeof AlbumClaimsRoute
  '/login': typeof LoginRoute
  '/marketplace-catalog': typeof MarketplaceCatalogRoute
  '/marketplace-inventory': typeof MarketplaceInventoryRoute
  '/marketplace-orders': typeof MarketplaceOrdersRoute
  '/notifications': typeof NotificationsRoute
  '/print-orders': typeof PrintOrdersRoute
  '/reels-catalog': typeof ReelsCatalogRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album-claims'
    | '/login'
    | '/marketplace-catalog'
    | '/marketplace-inventory'
    | '/marketplace-orders'
    | '/notifications'
    | '/print-orders'
    | '/reels-catalog'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album-claims'
    | '/login'
    | '/marketplace-catalog'
    | '/marketplace-inventory'
    | '/marketplace-orders'
    | '/notifications'
    | '/print-orders'
    | '/reels-catalog'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/album-claims'
    | '/login'
    | '/marketplace-catalog'
    | '/marketplace-inventory'
    | '/marketplace-orders'
    | '/notifications'
    | '/print-orders'
    | '/reels-catalog'
    | '/settings'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumClaimsRoute: typeof AlbumClaimsRoute
  LoginRoute: typeof LoginRoute
  MarketplaceCatalogRoute: typeof MarketplaceCatalogRoute
  MarketplaceInventoryRoute: typeof MarketplaceInventoryRoute
  MarketplaceOrdersRoute: typeof MarketplaceOrdersRoute
  NotificationsRoute: typeof NotificationsRoute
  PrintOrdersRoute: typeof PrintOrdersRoute
  ReelsCatalogRoute: typeof ReelsCatalogRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album-claims': {
      id: '/album-claims'
      path: '/album-claims'
      fullPath: '/album-claims'
      preLoaderRoute: typeof AlbumClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-catalog': {
      id: '/marketplace-catalog'
      path: '/marketplace-catalog'
      fullPath: '/marketplace-catalog'
      preLoaderRoute: typeof MarketplaceCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-inventory': {
      id: '/marketplace-inventory'
      path: '/marketplace-inventory'
      fullPath: '/marketplace-inventory'
      preLoaderRoute: typeof MarketplaceInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-orders': {
      id: '/marketplace-orders'
      path: '/marketplace-orders'
      fullPath: '/marketplace-orders'
      preLoaderRoute: typeof MarketplaceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-orders': {
      id: '/print-orders'
      path: '/print-orders'
      fullPath: '/print-orders'
      preLoaderRoute: typeof PrintOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels-catalog': {
      id: '/reels-catalog'
      path: '/reels-catalog'
      fullPath: '/reels-catalog'
      preLoaderRoute: typeof ReelsCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumClaimsRoute: AlbumClaimsRoute,
  LoginRoute: LoginRoute,
  MarketplaceCatalogRoute: MarketplaceCatalogRoute,
  MarketplaceInventoryRoute: MarketplaceInventoryRoute,
  MarketplaceOrdersRoute: MarketplaceOrdersRoute,
  NotificationsRoute: NotificationsRoute,
  PrintOrdersRoute: PrintOrdersRoute,
  ReelsCatalogRoute: ReelsCatalogRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
